### ISSUE TITLE
Search icon doesn't highlight when searching

### ISSUE THREAD

**Issue by ironmonk88** [ForgeVTT/forge-compendium-browser#17]

**Comment by rikmarais** [comment]
The search icon does not highlight, but also appears to be redundant since search is automatic upon input in 1.4.1 and the input field does get highlighted
![image](https://github.com/ForgeVTT/forge-compendium-browser/assets/34374883/74776c8e-5ef1-49ea-9d62-9d0eb318b85d)
![image](https://github.com/ForgeVTT/forge-compendium-browser/assets/34374883/f3b0a849-002b-42fe-b292-84b6ccd35164)

**Comment by ironmonk88** [comment]
![image](https://github.com/ForgeVTT/forge-compendium-browser/assets/75920956/9ace8c9c-c15e-4f0e-bc1c-ad5a1729b8b5)
This was the one that wasn't highlighting.
But you're right... it is kind of redundant now.

**Comment by illianne** [comment]
✅ Buttons highlighting as expected
